// <auto-generated />
namespace RailwaySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Schedules_Support1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Schedules_Support1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003031451296_Schedules_Support1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
