// <auto-generated />
namespace RailwaySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Update0903202202 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update0903202202));
        
        string IMigrationMetadata.Id
        {
            get { return "202203091405266_Update-09-03-2022-02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
