// <auto-generated />
namespace RailwaySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Update250422 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update250422));
        
        string IMigrationMetadata.Id
        {
            get { return "202204251011139_Update-25-04-22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
