// <auto-generated />
namespace RailwaySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Db_Update_03_02_2022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Db_Update_03_02_2022));
        
        string IMigrationMetadata.Id
        {
            get { return "202202031310499_Db_Update_03_02_2022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
